import type { Metadata } from "next";
import Link from "next/link";
import "@fontsource-variable/geist/wght.css";
import "@fontsource-variable/geist-mono/wght.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <header>
          <Link href="/" className="p-4 inline-block">
            IDPF Test App / Home
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
